import { GameSettings } from "./menu/settings";

// === LANGUAGE STRINGS ===
export const LANG = {
    ru: {
        play: "ИГРАТЬ",
        quickStart: "БЫСТРЫЙ СТАРТ",
        selectMap: "ВЫБОР КАРТЫ",
        garage: "ГАРАЖ",
        stats: "СТАТИСТИКА",
        skills: "НАВЫКИ",
        options: "НАСТРОЙКИ",
        controls: "УПРАВЛЕНИЕ",
        version: "Версия",
        tankCombat: "ТАНКОВЫЙ СИМУЛЯТОР",
        mapSelection: "ВЫБОР КАРТЫ",
        normalMap: "Эта самая карта",
        normalMapDesc: "Полностью случайная генерация с разнообразными биомами, дорогами и природой",
        sandboxMap: "Песочница",
        sandboxMapDesc: "Чистая плоская поверхность для тестирования",
        sandMap: "Песок",
        sandMapDesc: "Компактная двухуровневая арена в стиле Песочницы",
        madnessMap: "Безумие",
        madnessMapDesc: "Многоуровневая арена с мостиками, рампами и переходами",
        expoMap: "Экспо",
        expoMapDesc: "Киберспортивная арена среднего размера с множеством уровней",
        brestMap: "Брест",
        brestMapDesc: "Симметричная арена с крепостью в центре и базами по углам",
        arenaMap: "Арена",
        arenaMapDesc: "Киберспортивная арена с симметричной структурой и множеством тактических позиций",
        polygonMap: "Полигон",
        polygonMapDesc: "Военный полигон с ангарами, техникой, складами, кранами и вышками",
        frontlineMap: "Передовая",
        frontlineMapDesc: "Разрушенная линия фронта с кратерами, окопами и укреплениями",
        ruinsMap: "Руины",
        ruinsMapDesc: "Полуразрушенный город военного времени с обрушенными зданиями",
        canyonMap: "Ущелье",
        canyonMapDesc: "Горная местность с проходами, реками, озёрами, лесами и деревнями",
        industrialMap: "Промзона",
        industrialMapDesc: "Крупная промышленная зона с заводами, портом и ж/д терминалом",
        urbanWarfareMap: "Городские бои",
        urbanWarfareMapDesc: "Плотная городская застройка с баррикадами и укреплениями",
        undergroundMap: "Подземелье",
        undergroundMapDesc: "Система пещер, шахт и туннелей под землёй",
        coastalMap: "Побережье",
        coastalMapDesc: "Береговая линия с портом, маяками, пляжами и утёсами",
        tartariaMap: "Тартария",
        tartariaMapDesc: "Город Тарту на основе реальных данных высот (27-82м)",
        // Controls
        movement: "Движение",
        combat: "Бой",
        interface: "Интерфейс",
        camera: "Камера",
        comms: "Связь",
        moveTank: "Движение",
        rotateTurret: "Башня",
        turretLR: "Башня Л/П",
        fire: "Огонь",
        aimMode: "Прицел",
        useConsumables: "Расходники",
        zoom: "Зум",
        generalChat: "Общий чат",
        teamChat: "Командный чат",
        voicePTT: "Голосовой чат (PTT)",
        voiceToggle: "Вкл/Выкл голосовой связи",
        voiceMenu: "Меню/индикатор голоса",
        tracerHotkey: "Трассер",
        admin: "Админ",
        adminTools: "Админ-инструменты",
        adminCheatPanel: "Окно контроля читов",
        adminF2: "Настройки скриншота (Ctrl+2)",
        adminF3: "Dev Dashboard (Ctrl+3)",
        adminF4: "Dev Console (Ctrl+4)",
        adminF6: "Настройки физики (Ctrl+6)",
        adminF7: "Меню читов (Ctrl+7)",
        openCheatMenu: "Открыть меню читов",
        garageKey: "Гараж",
        map: "Карта",
        statsKey: "Статистика",
        pauseMenu: "Пауза / Меню",
        freeLook: "Свободный обзор",
        center: "Центрировать",
        barrelPitch: "Наклон ствола",
        barrelUp: "Поднять ствол",
        barrelDown: "Опустить ствол",
        cameraTilt: "Наклон камеры",
        aimKey: "Прицеливание",
        gameCursor: "Игровой курсор",
        garageMenu: "Меню гаража",
        missions: "Панель миссий",
        consumables6to9: "Расходники 6-9",
        adminF2Key: "F2",
        adminF3Key: "F3",
        adminF4Key: "F4",
        adminF5Key: "F5",
        adminF6Key: "F6",
        adminF7Key: "F7",
        // Settings
        sound: "Звук",
        music: "Музыка",
        graphics: "Графика",
        language: "Язык",
        enemyDifficulty: "Сложность ботов",
        diffEasy: "ЛЕГКО",
        diffMedium: "СРЕДНЕ",
        diffHard: "СЛОЖНО",
        worldSeed: "Сид карты",
        randomSeed: "Случайный сид",
        copySeed: "Копировать",
        seedCopied: "Сид скопирован!",
        fullscreen: "Полный экран",
        exitFullscreen: "Выйти из полноэкранного",
        close: "ЗАКРЫТЬ",
        apply: "ПРИМЕНИТЬ",
        reset: "СБРОС",
        // Stats
        kills: "Убийств",
        deaths: "Смертей",
        playtime: "Время игры",
        credits: "Кредиты",
        // Garage
        chassis: "КОРПУСА",
        cannons: "ОРУДИЯ",
        upgrades: "УЛУЧШЕНИЯ",
        locked: "ЗАБЛОКИРОВАНО",
        owned: "КУПЛЕНО",
        buy: "КУПИТЬ",
        select: "ВЫБРАТЬ",
        maxLevel: "МАКС",
        upgrade: "УЛУЧШИТЬ",
        notEnoughCredits: "Недостаточно кредитов!"
    },
    en: {
        play: "PLAY",
        quickStart: "QUICK START",
        selectMap: "SELECT MAP",
        garage: "GARAGE",
        stats: "STATS",
        skills: "SKILLS",
        options: "OPTIONS",
        controls: "CONTROLS",
        version: "Version",
        tankCombat: "TANK SIMULATOR",
        mapSelection: "MAP SELECTION",
        normalMap: "Normal Map",
        normalMapDesc: "Fully random generation with diverse biomes, roads and nature",
        sandboxMap: "Sandbox",
        sandboxMapDesc: "Clean flat surface for testing",
        sandMap: "Sand",
        sandMapDesc: "Compact two-level arena in Sandbox style",
        madnessMap: "Madness",
        madnessMapDesc: "Multi-level arena with bridges, ramps and passages",
        expoMap: "Expo",
        expoMapDesc: "Medium-sized esports arena with multiple levels",
        brestMap: "Brest",
        brestMapDesc: "Symmetric arena with fortress in center and corner bases",
        arenaMap: "Arena",
        arenaMapDesc: "Esports arena with symmetric structure and multiple tactical positions",
        polygonMap: "Training Ground",
        polygonMapDesc: "Military training ground with hangars, vehicles, warehouses, cranes and watchtowers",
        frontlineMap: "Frontline",
        frontlineMapDesc: "Destroyed frontline with craters, trenches and fortifications",
        ruinsMap: "Ruins",
        ruinsMapDesc: "Half-destroyed war-torn city with collapsed buildings",
        canyonMap: "Canyon",
        canyonMapDesc: "Mountainous terrain with passes, rivers, lakes, forests and villages",
        industrialMap: "Industrial Zone",
        industrialMapDesc: "Large industrial area with factories, port and railway terminal",
        urbanWarfareMap: "Urban Warfare",
        urbanWarfareMapDesc: "Dense urban environment with barricades and fortifications",
        undergroundMap: "Underground",
        undergroundMapDesc: "Cave system, mines and tunnels underground",
        coastalMap: "Coastal",
        coastalMapDesc: "Coastline with port, lighthouses, beaches and cliffs",
        tartariaMap: "Tartaria",
        tartariaMapDesc: "City of Tartu based on real elevation data (27-82m)",
        // Controls
        movement: "Movement",
        combat: "Combat",
        interface: "Interface",
        camera: "Camera",
        comms: "Comms",
        moveTank: "Move tank",
        rotateTurret: "Rotate turret",
        turretLR: "Turret L/R",
        fire: "Fire",
        aimMode: "Aim mode",
        useConsumables: "Use consumables",
        zoom: "Zoom (aim)",
        generalChat: "General chat",
        teamChat: "Team chat",
        voicePTT: "Voice chat (PTT)",
        voiceToggle: "Voice toggle on/off",
        voiceMenu: "Voice menu/indicator",
        tracerHotkey: "Tracer",
        admin: "Admin",
        adminTools: "Admin tools",
        adminCheatPanel: "Cheat control window",
        adminF2: "Screenshot settings (Ctrl+2)",
        adminF3: "Dev Dashboard (Ctrl+3)",
        adminF4: "Dev Console (Ctrl+4)",
        adminF6: "Physics settings (Ctrl+6)",
        adminF7: "Cheat menu (Ctrl+7)",
        openCheatMenu: "Open cheat menu",
        garageKey: "Garage",
        map: "Map",
        statsKey: "Stats",
        pauseMenu: "Pause / Menu",
        freeLook: "Free look",
        center: "Center",
        barrelPitch: "Barrel Pitch",
        barrelUp: "Raise Barrel",
        barrelDown: "Lower Barrel",
        cameraTilt: "Camera Tilt",
        aimKey: "Aiming",
        gameCursor: "Game Cursor",
        garageMenu: "Garage Menu",
        missions: "Missions Panel",
        consumables6to9: "Consumables 6-9",
        adminF2Key: "F2",
        adminF3Key: "F3",
        adminF4Key: "F4",
        adminF5Key: "F5",
        adminF6Key: "F6",
        adminF7Key: "F7",
        // Settings
        sound: "Sound",
        music: "Music",
        graphics: "Graphics",
        language: "Language",
        enemyDifficulty: "Bot Difficulty",
        diffEasy: "EASY",
        diffMedium: "MEDIUM",
        diffHard: "HARD",
        worldSeed: "World Seed",
        randomSeed: "Random Seed",
        copySeed: "Copy",
        seedCopied: "Seed copied!",
        fullscreen: "Fullscreen",
        exitFullscreen: "Exit Fullscreen",
        close: "CLOSE",
        apply: "APPLY",
        reset: "RESET",
        // Stats
        kills: "Kills",
        deaths: "Deaths",
        playtime: "Playtime",
        credits: "Credits",
        // Garage
        chassis: "CHASSIS",
        cannons: "CANNONS",
        upgrades: "UPGRADES",
        locked: "LOCKED",
        owned: "OWNED",
        buy: "BUY",
        select: "SELECT",
        maxLevel: "MAX",
        upgrade: "UPGRADE",
        notEnoughCredits: "Not enough credits!"
    }
};

// Get current language strings
export function getLang(settings: GameSettings): typeof LANG.ru {
    return LANG[settings.language as keyof typeof LANG] || LANG.ru;
}
